/* eslint-disable comma-spacing */

export const iconList = {
	"Accessibility": ["fab fa-accessible-icon","fas fa-american-sign-language-interpreting","fas fa-assistive-listening-systems","fas fa-audio-description","fas fa-blind","fas fa-braille","fas fa-closed-captioning","far fa-closed-captioning","fas fa-deaf","fas fa-low-vision","fas fa-phone-volume","fas fa-question-circle","far fa-question-circle","fas fa-sign-language","fas fa-tty","fas fa-universal-access","fas fa-wheelchair"],
	"Alert": ["fas fa-bell","far fa-bell","fas fa-bell-slash","far fa-bell-slash","fas fa-exclamation","fas fa-exclamation-circle","fas fa-exclamation-triangle","fas fa-radiation","fas fa-radiation-alt","fas fa-skull-crossbones"],
	"Animals": ["fas fa-cat","fas fa-crow","fas fa-dog","fas fa-dove","fas fa-dragon","fas fa-feather","fas fa-feather-alt","fas fa-fish","fas fa-frog","fas fa-hippo","fas fa-horse","fas fa-horse-head","fas fa-kiwi-bird","fas fa-otter","fas fa-paw","fas fa-spider"],
	"Arrows": ["fas fa-angle-double-down","fas fa-angle-double-left","fas fa-angle-double-right","fas fa-angle-double-up","fas fa-angle-down","fas fa-angle-left","fas fa-angle-right","fas fa-angle-up","fas fa-arrow-alt-circle-down","far fa-arrow-alt-circle-down","fas fa-arrow-alt-circle-left","far fa-arrow-alt-circle-left","fas fa-arrow-alt-circle-right","far fa-arrow-alt-circle-right","fas fa-arrow-alt-circle-up","far fa-arrow-alt-circle-up","fas fa-arrow-circle-down","fas fa-arrow-circle-left","fas fa-arrow-circle-right","fas fa-arrow-circle-up","fas fa-arrow-down","fas fa-arrow-left","fas fa-arrow-right","fas fa-arrow-up","fas fa-arrows-alt","fas fa-arrows-alt-h","fas fa-arrows-alt-v","fas fa-caret-down","fas fa-caret-left","fas fa-caret-right","fas fa-caret-square-down","far fa-caret-square-down","fas fa-caret-square-left","far fa-caret-square-left","fas fa-caret-square-right","far fa-caret-square-right","fas fa-caret-square-up","far fa-caret-square-up","fas fa-caret-up","fas fa-cart-arrow-down","fas fa-chart-line","fas fa-chevron-circle-down","fas fa-chevron-circle-left","fas fa-chevron-circle-right","fas fa-chevron-circle-up","fas fa-chevron-down","fas fa-chevron-left","fas fa-chevron-right","fas fa-chevron-up","fas fa-cloud-download-alt","fas fa-cloud-upload-alt","fas fa-compress-arrows-alt","fas fa-download","fas fa-exchange-alt","fas fa-expand-arrows-alt","fas fa-external-link-alt","fas fa-external-link-square-alt","fas fa-hand-point-down","far fa-hand-point-down","fas fa-hand-point-left","far fa-hand-point-left","fas fa-hand-point-right","far fa-hand-point-right","fas fa-hand-point-up","far fa-hand-point-up","fas fa-hand-pointer","far fa-hand-pointer","fas fa-history","fas fa-level-down-alt","fas fa-level-up-alt","fas fa-location-arrow","fas fa-long-arrow-alt-down","fas fa-long-arrow-alt-left","fas fa-long-arrow-alt-right","fas fa-long-arrow-alt-up","fas fa-mouse-pointer","fas fa-play","fas fa-random","fas fa-recycle","fas fa-redo","fas fa-redo-alt","fas fa-reply","fas fa-reply-all","fas fa-retweet","fas fa-share","fas fa-share-square","far fa-share-square","fas fa-sign-in-alt","fas fa-sign-out-alt","fas fa-sort","fas fa-sort-alpha-down","fas fa-sort-alpha-down-alt","fas fa-sort-alpha-up","fas fa-sort-alpha-up-alt","fas fa-sort-amount-down","fas fa-sort-amount-down-alt","fas fa-sort-amount-up","fas fa-sort-amount-up-alt","fas fa-sort-down","fas fa-sort-numeric-down","fas fa-sort-numeric-down-alt","fas fa-sort-numeric-up","fas fa-sort-numeric-up-alt","fas fa-sort-up","fas fa-sync","fas fa-sync-alt","fas fa-text-height","fas fa-text-width","fas fa-undo","fas fa-undo-alt","fas fa-upload"],
	"Automotive": ["fas fa-air-freshener","fas fa-ambulance","fas fa-bus","fas fa-bus-alt","fas fa-car","fas fa-car-alt","fas fa-car-battery","fas fa-car-crash","fas fa-car-side","fas fa-charging-station","fas fa-gas-pump","fas fa-motorcycle","fas fa-oil-can","fas fa-shuttle-van","fas fa-tachometer-alt","fas fa-taxi","fas fa-truck","fas fa-truck-monster","fas fa-truck-pickup"],
	"Autumn": ["fas fa-apple-alt","fas fa-campground","fas fa-cloud-sun","fas fa-drumstick-bite","fas fa-football-ball","fas fa-hiking","fas fa-mountain","fas fa-tractor","fas fa-tree","fas fa-wind","fas fa-wine-bottle"],
	"Beverage": ["fas fa-beer","fas fa-blender","fas fa-cocktail","fas fa-coffee","fas fa-flask","fas fa-glass-cheers","fas fa-glass-martini","fas fa-glass-martini-alt","fas fa-glass-whiskey","fas fa-mug-hot","fas fa-wine-bottle","fas fa-wine-glass","fas fa-wine-glass-alt"],
	"Buildings": ["fas fa-archway","fas fa-building","far fa-building","fas fa-campground","fas fa-church","fas fa-city","fas fa-clinic-medical","fas fa-dungeon","fas fa-gopuram","fas fa-home","fas fa-hospital","far fa-hospital","fas fa-hospital-alt","fas fa-hotel","fas fa-house-damage","fas fa-igloo","fas fa-industry","fas fa-kaaba","fas fa-landmark","fas fa-monument","fas fa-mosque","fas fa-place-of-worship","fas fa-school","fas fa-store","fas fa-store-alt","fas fa-synagogue","fas fa-torii-gate","fas fa-university","fas fa-vihara","fas fa-warehouse"],
	"Business": ["fas fa-address-book","far fa-address-book","fas fa-address-card","far fa-address-card","fas fa-archive","fas fa-balance-scale","fas fa-balance-scale-left","fas fa-balance-scale-right","fas fa-birthday-cake","fas fa-book","fas fa-briefcase","fas fa-building","far fa-building","fas fa-bullhorn","fas fa-bullseye","fas fa-business-time","fas fa-calculator","fas fa-calendar","far fa-calendar","fas fa-calendar-alt","far fa-calendar-alt","fas fa-certificate","fas fa-chart-area","fas fa-chart-bar","far fa-chart-bar","fas fa-chart-line","fas fa-chart-pie","fas fa-city","fas fa-clipboard","far fa-clipboard","fas fa-coffee","fas fa-columns","fas fa-compass","far fa-compass","fas fa-copy","far fa-copy","fas fa-copyright","far fa-copyright","fas fa-cut","fas fa-edit","far fa-edit","fas fa-envelope","far fa-envelope","fas fa-envelope-open","far fa-envelope-open","fas fa-envelope-square","fas fa-eraser","fas fa-fax","fas fa-file","far fa-file","fas fa-file-alt","far fa-file-alt","fas fa-folder","far fa-folder","fas fa-folder-minus","fas fa-folder-open","far fa-folder-open","fas fa-folder-plus","fas fa-glasses","fas fa-globe","fas fa-highlighter","fas fa-industry","fas fa-landmark","fas fa-marker","fas fa-paperclip","fas fa-paste","fas fa-pen","fas fa-pen-alt","fas fa-pen-fancy","fas fa-pen-nib","fas fa-pen-square","fas fa-pencil-alt","fas fa-percent","fas fa-phone","fas fa-phone-alt","fas fa-phone-slash","fas fa-phone-square","fas fa-phone-square-alt","fas fa-phone-volume","fas fa-print","fas fa-project-diagram","fas fa-registered","far fa-registered","fas fa-save","far fa-save","fas fa-sitemap","fas fa-socks","fas fa-sticky-note","far fa-sticky-note","fas fa-stream","fas fa-table","fas fa-tag","fas fa-tags","fas fa-tasks","fas fa-thumbtack","fas fa-trademark","fas fa-wallet"],
	"Camping": ["fas fa-binoculars","fas fa-campground","fas fa-compass","far fa-compass","fas fa-fire","fas fa-fire-alt","fas fa-first-aid","fas fa-frog","fas fa-hiking","fas fa-map","far fa-map","fas fa-map-marked","fas fa-map-marked-alt","fas fa-map-signs","fas fa-mountain","fas fa-route","fas fa-toilet-paper","fas fa-tree"],
	"Charity": ["fas fa-dollar-sign","fas fa-donate","fas fa-dove","fas fa-gift","fas fa-globe","fas fa-hand-holding-heart","fas fa-hand-holding-usd","fas fa-hands-helping","fas fa-handshake","far fa-handshake","fas fa-heart","far fa-heart","fas fa-leaf","fas fa-parachute-box","fas fa-piggy-bank","fas fa-ribbon","fas fa-seedling"],
	"Chat": ["fas fa-comment","far fa-comment","fas fa-comment-alt","far fa-comment-alt","fas fa-comment-dots","far fa-comment-dots","fas fa-comment-medical","fas fa-comment-slash","fas fa-comments","far fa-comments","fas fa-frown","far fa-frown","fas fa-icons","fas fa-meh","far fa-meh","fas fa-phone","fas fa-phone-alt","fas fa-phone-slash","fas fa-poo","fas fa-quote-left","fas fa-quote-right","fas fa-smile","far fa-smile","fas fa-sms","fas fa-video","fas fa-video-slash"],
	"Chess": ["fas fa-chess","fas fa-chess-bishop","fas fa-chess-board","fas fa-chess-king","fas fa-chess-knight","fas fa-chess-pawn","fas fa-chess-queen","fas fa-chess-rook","fas fa-square-full"],
	"Childhood": ["fas fa-apple-alt","fas fa-baby","fas fa-baby-carriage","fas fa-bath","fas fa-biking","fas fa-birthday-cake","fas fa-cookie","fas fa-cookie-bite","fas fa-ice-cream","fas fa-mitten","fas fa-robot","fas fa-school","fas fa-shapes","fas fa-snowman"],
	"Clothing": ["fas fa-graduation-cap","fas fa-hat-wizard","fas fa-mitten","fas fa-shoe-prints","fas fa-socks","fas fa-tshirt","fas fa-user-tie"],
	"Code": ["fas fa-archive","fas fa-barcode","fas fa-bath","fas fa-bug","fas fa-code","fas fa-code-branch","fas fa-coffee","fas fa-file","far fa-file","fas fa-file-alt","far fa-file-alt","fas fa-file-code","far fa-file-code","fas fa-filter","fas fa-fire-extinguisher","fas fa-folder","far fa-folder","fas fa-folder-open","far fa-folder-open","fas fa-keyboard","far fa-keyboard","fas fa-laptop-code","fas fa-microchip","fas fa-project-diagram","fas fa-qrcode","fas fa-shield-alt","fas fa-sitemap","fas fa-stream","fas fa-terminal","fas fa-user-secret","fas fa-window-close","far fa-window-close","fas fa-window-maximize","far fa-window-maximize","fas fa-window-minimize","far fa-window-minimize","fas fa-window-restore","far fa-window-restore"],
	"Communication": ["fas fa-address-book","far fa-address-book","fas fa-address-card","far fa-address-card","fas fa-american-sign-language-interpreting","fas fa-assistive-listening-systems","fas fa-at","fas fa-bell","far fa-bell","fas fa-bell-slash","far fa-bell-slash","fab fa-bluetooth","fab fa-bluetooth-b","fas fa-broadcast-tower","fas fa-bullhorn","fas fa-chalkboard","fas fa-comment","far fa-comment","fas fa-comment-alt","far fa-comment-alt","fas fa-comments","far fa-comments","fas fa-envelope","far fa-envelope","fas fa-envelope-open","far fa-envelope-open","fas fa-envelope-square","fas fa-fax","fas fa-inbox","fas fa-language","fas fa-microphone","fas fa-microphone-alt","fas fa-microphone-alt-slash","fas fa-microphone-slash","fas fa-mobile","fas fa-mobile-alt","fas fa-paper-plane","far fa-paper-plane","fas fa-phone","fas fa-phone-alt","fas fa-phone-slash","fas fa-phone-square","fas fa-phone-square-alt","fas fa-phone-volume","fas fa-rss","fas fa-rss-square","fas fa-tty","fas fa-voicemail","fas fa-wifi"],
	"Computers": ["fas fa-database","fas fa-desktop","fas fa-download","fas fa-ethernet","fas fa-hdd","far fa-hdd","fas fa-headphones","fas fa-keyboard","far fa-keyboard","fas fa-laptop","fas fa-memory","fas fa-microchip","fas fa-mobile","fas fa-mobile-alt","fas fa-plug","fas fa-power-off","fas fa-print","fas fa-satellite","fas fa-satellite-dish","fas fa-save","far fa-save","fas fa-sd-card","fas fa-server","fas fa-sim-card","fas fa-stream","fas fa-tablet","fas fa-tablet-alt","fas fa-tv","fas fa-upload"],
	"Construction": ["fas fa-brush","fas fa-drafting-compass","fas fa-dumpster","fas fa-hammer","fas fa-hard-hat","fas fa-paint-roller","fas fa-pencil-alt","fas fa-pencil-ruler","fas fa-ruler","fas fa-ruler-combined","fas fa-ruler-horizontal","fas fa-ruler-vertical","fas fa-screwdriver","fas fa-toolbox","fas fa-tools","fas fa-truck-pickup","fas fa-wrench"],
	"Currency": ["fab fa-bitcoin","fab fa-btc","fas fa-dollar-sign","fab fa-ethereum","fas fa-euro-sign","fab fa-gg","fab fa-gg-circle","fas fa-hryvnia","fas fa-lira-sign","fas fa-money-bill","fas fa-money-bill-alt","far fa-money-bill-alt","fas fa-money-bill-wave","fas fa-money-bill-wave-alt","fas fa-money-check","fas fa-money-check-alt","fas fa-pound-sign","fas fa-ruble-sign","fas fa-rupee-sign","fas fa-shekel-sign","fas fa-tenge","fas fa-won-sign","fas fa-yen-sign"],
	"Date and Time": ["fas fa-bell","far fa-bell","fas fa-bell-slash","far fa-bell-slash","fas fa-calendar","far fa-calendar","fas fa-calendar-alt","far fa-calendar-alt","fas fa-calendar-check","far fa-calendar-check","fas fa-calendar-minus","far fa-calendar-minus","fas fa-calendar-plus","far fa-calendar-plus","fas fa-calendar-times","far fa-calendar-times","fas fa-clock","far fa-clock","fas fa-hourglass","far fa-hourglass","fas fa-hourglass-end","fas fa-hourglass-half","fas fa-hourglass-start","fas fa-stopwatch"],
	"Design": ["fas fa-adjust","fas fa-bezier-curve","fas fa-brush","fas fa-clone","far fa-clone","fas fa-copy","far fa-copy","fas fa-crop","fas fa-crop-alt","fas fa-crosshairs","fas fa-cut","fas fa-drafting-compass","fas fa-draw-polygon","fas fa-edit","far fa-edit","fas fa-eraser","fas fa-eye","far fa-eye","fas fa-eye-dropper","fas fa-eye-slash","far fa-eye-slash","fas fa-fill","fas fa-fill-drip","fas fa-highlighter","fas fa-icons","fas fa-layer-group","fas fa-magic","fas fa-marker","fas fa-object-group","far fa-object-group","fas fa-object-ungroup","far fa-object-ungroup","fas fa-paint-brush","fas fa-paint-roller","fas fa-palette","fas fa-paste","fas fa-pen","fas fa-pen-alt","fas fa-pen-fancy","fas fa-pen-nib","fas fa-pencil-alt","fas fa-pencil-ruler","fas fa-ruler-combined","fas fa-ruler-horizontal","fas fa-ruler-vertical","fas fa-save","far fa-save","fas fa-splotch","fas fa-spray-can","fas fa-stamp","fas fa-swatchbook","fas fa-tint","fas fa-tint-slash","fas fa-vector-square"],
	"Editors": ["fas fa-align-center","fas fa-align-justify","fas fa-align-left","fas fa-align-right","fas fa-bold","fas fa-border-all","fas fa-border-none","fas fa-border-style","fas fa-clipboard","far fa-clipboard","fas fa-clone","far fa-clone","fas fa-columns","fas fa-copy","far fa-copy","fas fa-cut","fas fa-edit","far fa-edit","fas fa-eraser","fas fa-file","far fa-file","fas fa-file-alt","far fa-file-alt","fas fa-font","fas fa-glasses","fas fa-heading","fas fa-highlighter","fas fa-i-cursor","fas fa-icons","fas fa-indent","fas fa-italic","fas fa-link","fas fa-list","fas fa-list-alt","far fa-list-alt","fas fa-list-ol","fas fa-list-ul","fas fa-marker","fas fa-outdent","fas fa-paper-plane","far fa-paper-plane","fas fa-paperclip","fas fa-paragraph","fas fa-paste","fas fa-pen","fas fa-pen-alt","fas fa-pen-fancy","fas fa-pen-nib","fas fa-pencil-alt","fas fa-print","fas fa-quote-left","fas fa-quote-right","fas fa-redo","fas fa-redo-alt","fas fa-remove-format","fas fa-reply","fas fa-reply-all","fas fa-screwdriver","fas fa-share","fas fa-spell-check","fas fa-strikethrough","fas fa-subscript","fas fa-superscript","fas fa-sync","fas fa-sync-alt","fas fa-table","fas fa-tasks","fas fa-text-height","fas fa-text-width","fas fa-th","fas fa-th-large","fas fa-th-list","fas fa-tools","fas fa-trash","fas fa-trash-alt","far fa-trash-alt","fas fa-trash-restore","fas fa-trash-restore-alt","fas fa-underline","fas fa-undo","fas fa-undo-alt","fas fa-unlink","fas fa-wrench"],
	"Education": ["fas fa-apple-alt","fas fa-atom","fas fa-award","fas fa-bell","far fa-bell","fas fa-bell-slash","far fa-bell-slash","fas fa-book-open","fas fa-book-reader","fas fa-chalkboard","fas fa-chalkboard-teacher","fas fa-graduation-cap","fas fa-laptop-code","fas fa-microscope","fas fa-music","fas fa-school","fas fa-shapes","fas fa-theater-masks","fas fa-user-graduate"],
	"Emoji": ["fas fa-angry","far fa-angry","fas fa-dizzy","far fa-dizzy","fas fa-flushed","far fa-flushed","fas fa-frown","far fa-frown","fas fa-frown-open","far fa-frown-open","fas fa-grimace","far fa-grimace","fas fa-grin","far fa-grin","fas fa-grin-alt","far fa-grin-alt","fas fa-grin-beam","far fa-grin-beam","fas fa-grin-beam-sweat","far fa-grin-beam-sweat","fas fa-grin-hearts","far fa-grin-hearts","fas fa-grin-squint","far fa-grin-squint","fas fa-grin-squint-tears","far fa-grin-squint-tears","fas fa-grin-stars","far fa-grin-stars","fas fa-grin-tears","far fa-grin-tears","fas fa-grin-tongue","far fa-grin-tongue","fas fa-grin-tongue-squint","far fa-grin-tongue-squint","fas fa-grin-tongue-wink","far fa-grin-tongue-wink","fas fa-grin-wink","far fa-grin-wink","fas fa-kiss","far fa-kiss","fas fa-kiss-beam","far fa-kiss-beam","fas fa-kiss-wink-heart","far fa-kiss-wink-heart","fas fa-laugh","far fa-laugh","fas fa-laugh-beam","far fa-laugh-beam","fas fa-laugh-squint","far fa-laugh-squint","fas fa-laugh-wink","far fa-laugh-wink","fas fa-meh","far fa-meh","fas fa-meh-blank","far fa-meh-blank","fas fa-meh-rolling-eyes","far fa-meh-rolling-eyes","fas fa-sad-cry","far fa-sad-cry","fas fa-sad-tear","far fa-sad-tear","fas fa-smile","far fa-smile","fas fa-smile-beam","far fa-smile-beam","fas fa-smile-wink","far fa-smile-wink","fas fa-surprise","far fa-surprise","fas fa-tired","far fa-tired"],
	"Energy": ["fas fa-atom","fas fa-battery-empty","fas fa-battery-full","fas fa-battery-half","fas fa-battery-quarter","fas fa-battery-three-quarters","fas fa-broadcast-tower","fas fa-burn","fas fa-charging-station","fas fa-fire","fas fa-fire-alt","fas fa-gas-pump","fas fa-industry","fas fa-leaf","fas fa-lightbulb","far fa-lightbulb","fas fa-plug","fas fa-poop","fas fa-power-off","fas fa-radiation","fas fa-radiation-alt","fas fa-seedling","fas fa-solar-panel","fas fa-sun","far fa-sun","fas fa-water","fas fa-wind"],
	"Files": ["fas fa-archive","fas fa-clone","far fa-clone","fas fa-copy","far fa-copy","fas fa-cut","fas fa-file","far fa-file","fas fa-file-alt","far fa-file-alt","fas fa-file-archive","far fa-file-archive","fas fa-file-audio","far fa-file-audio","fas fa-file-code","far fa-file-code","fas fa-file-excel","far fa-file-excel","fas fa-file-image","far fa-file-image","fas fa-file-pdf","far fa-file-pdf","fas fa-file-powerpoint","far fa-file-powerpoint","fas fa-file-video","far fa-file-video","fas fa-file-word","far fa-file-word","fas fa-folder","far fa-folder","fas fa-folder-open","far fa-folder-open","fas fa-paste","fas fa-photo-video","fas fa-save","far fa-save","fas fa-sticky-note","far fa-sticky-note"],
	"Finance": ["fas fa-balance-scale","fas fa-balance-scale-left","fas fa-balance-scale-right","fas fa-book","fas fa-cash-register","fas fa-chart-line","fas fa-chart-pie","fas fa-coins","fas fa-comment-dollar","fas fa-comments-dollar","fas fa-credit-card","far fa-credit-card","fas fa-donate","fas fa-file-invoice","fas fa-file-invoice-dollar","fas fa-hand-holding-usd","fas fa-landmark","fas fa-money-bill","fas fa-money-bill-alt","far fa-money-bill-alt","fas fa-money-bill-wave","fas fa-money-bill-wave-alt","fas fa-money-check","fas fa-money-check-alt","fas fa-percentage","fas fa-piggy-bank","fas fa-receipt","fas fa-stamp","fas fa-wallet"],
	"Fitness": ["fas fa-bicycle","fas fa-biking","fas fa-burn","fas fa-fire-alt","fas fa-heart","far fa-heart","fas fa-heartbeat","fas fa-hiking","fas fa-running","fas fa-shoe-prints","fas fa-skating","fas fa-skiing","fas fa-skiing-nordic","fas fa-snowboarding","fas fa-spa","fas fa-swimmer","fas fa-walking"],
	"Food": ["fas fa-apple-alt","fas fa-bacon","fas fa-bone","fas fa-bread-slice","fas fa-candy-cane","fas fa-carrot","fas fa-cheese","fas fa-cloud-meatball","fas fa-cookie","fas fa-drumstick-bite","fas fa-egg","fas fa-fish","fas fa-hamburger","fas fa-hotdog","fas fa-ice-cream","fas fa-lemon","far fa-lemon","fas fa-pepper-hot","fas fa-pizza-slice","fas fa-seedling","fas fa-stroopwafel"],
	"Games": ["fas fa-chess","fas fa-chess-bishop","fas fa-chess-board","fas fa-chess-king","fas fa-chess-knight","fas fa-chess-pawn","fas fa-chess-queen","fas fa-chess-rook","fas fa-dice","fas fa-dice-d20","fas fa-dice-d6","fas fa-dice-five","fas fa-dice-four","fas fa-dice-one","fas fa-dice-six","fas fa-dice-three","fas fa-dice-two","fas fa-gamepad","fas fa-ghost","fas fa-headset","fas fa-heart","far fa-heart","fab fa-playstation","fas fa-puzzle-piece","fab fa-steam","fab fa-steam-square","fab fa-steam-symbol","fab fa-twitch","fab fa-xbox"],
	"Hands": ["fas fa-allergies","fas fa-fist-raised","fas fa-hand-holding","fas fa-hand-holding-heart","fas fa-hand-holding-usd","fas fa-hand-lizard","far fa-hand-lizard","fas fa-hand-middle-finger","fas fa-hand-paper","far fa-hand-paper","fas fa-hand-peace","far fa-hand-peace","fas fa-hand-point-down","far fa-hand-point-down","fas fa-hand-point-left","far fa-hand-point-left","fas fa-hand-point-right","far fa-hand-point-right","fas fa-hand-point-up","far fa-hand-point-up","fas fa-hand-pointer","far fa-hand-pointer","fas fa-hand-rock","far fa-hand-rock","fas fa-hand-scissors","far fa-hand-scissors","fas fa-hand-spock","far fa-hand-spock","fas fa-hands","fas fa-hands-helping","fas fa-handshake","far fa-handshake","fas fa-praying-hands","fas fa-thumbs-down","far fa-thumbs-down","fas fa-thumbs-up","far fa-thumbs-up"],
	"Health": ["fab fa-accessible-icon","fas fa-ambulance","fas fa-h-square","fas fa-heart","far fa-heart","fas fa-heartbeat","fas fa-hospital","far fa-hospital","fas fa-medkit","fas fa-plus-square","far fa-plus-square","fas fa-prescription","fas fa-stethoscope","fas fa-user-md","fas fa-wheelchair"],
	"Hotel": ["fas fa-baby-carriage","fas fa-bath","fas fa-bed","fas fa-briefcase","fas fa-car","fas fa-cocktail","fas fa-coffee","fas fa-concierge-bell","fas fa-dice","fas fa-dice-five","fas fa-door-closed","fas fa-door-open","fas fa-dumbbell","fas fa-glass-martini","fas fa-glass-martini-alt","fas fa-hot-tub","fas fa-hotel","fas fa-infinity","fas fa-key","fas fa-luggage-cart","fas fa-shower","fas fa-shuttle-van","fas fa-smoking","fas fa-smoking-ban","fas fa-snowflake","far fa-snowflake","fas fa-spa","fas fa-suitcase","fas fa-suitcase-rolling","fas fa-swimmer","fas fa-swimming-pool","fas fa-tv","fas fa-umbrella-beach","fas fa-utensils","fas fa-wheelchair","fas fa-wifi"],
	"Household": ["fas fa-bath","fas fa-bed","fas fa-blender","fas fa-chair","fas fa-couch","fas fa-door-closed","fas fa-door-open","fas fa-dungeon","fas fa-fan","fas fa-shower","fas fa-toilet-paper","fas fa-tv","fas fa-box","fas fa-boxes","fas fa-clipboard-check","fas fa-clipboard-list","fas fa-dolly","fas fa-dolly-flatbed","fas fa-hard-hat","fas fa-pallet","fas fa-shipping-fast","fas fa-truck","fas fa-warehouse"],
	"Maritime": ["fas fa-anchor","fas fa-binoculars","fas fa-compass","far fa-compass","fas fa-dharmachakra","fas fa-frog","fas fa-ship","fas fa-skull-crossbones","fas fa-swimmer","fas fa-water","fas fa-wind"],
	// CURRENTLY AT MARKETING
	"Media": ["fas fa-audio-description","fas fa-backward","fas fa-broadcast-tower","fas fa-circle","far fa-circle","fas fa-closed-captioning","far fa-closed-captioning","fas fa-compress","fas fa-compress-arrows-alt","fas fa-eject","fas fa-expand","fas fa-expand-arrows-alt","fas fa-fast-backward","fas fa-fast-forward","fas fa-file-audio","far fa-file-audio","fas fa-file-video","far fa-file-video","fas fa-film","fas fa-forward","fas fa-headphones","fas fa-microphone","fas fa-microphone-alt","fas fa-microphone-alt-slash","fas fa-microphone-slash","fas fa-music","fas fa-pause","fas fa-pause-circle","far fa-pause-circle","fas fa-phone-volume","fas fa-photo-video","fas fa-play","fas fa-play-circle","far fa-play-circle","fas fa-podcast","fas fa-random","fas fa-redo","fas fa-redo-alt","fas fa-rss","fas fa-rss-square","fas fa-step-backward","fas fa-step-forward","fas fa-stop","fas fa-stop-circle","far fa-stop-circle","fas fa-sync","fas fa-sync-alt","fas fa-undo","fas fa-undo-alt","fas fa-video","fas fa-volume-down","fas fa-volume-mute","fas fa-volume-off","fas fa-volume-up","fab fa-youtube"],
	"Seasonal": ["fas fa-book-dead","fas fa-broom","fas fa-cat","fas fa-cloud-moon","fas fa-crow","fas fa-ghost","fas fa-hat-wizard","fas fa-mask","fas fa-skull-crossbones","fas fa-spider","fas fa-toilet-paper", "fas fa-candy-cane","fas fa-carrot","fas fa-cookie-bite","fas fa-gift","fas fa-gifts","fas fa-glass-cheers","fas fa-holly-berry","fas fa-mug-hot","fas fa-sleigh","fas fa-snowman"],
	"Signs": ["fas fa-ambulance","fas fa-anchor","fas fa-balance-scale","fas fa-balance-scale-left","fas fa-balance-scale-right","fas fa-bath","fas fa-bed","fas fa-beer","fas fa-bell","far fa-bell","fas fa-bell-slash","far fa-bell-slash","fas fa-bicycle","fas fa-binoculars","fas fa-birthday-cake","fas fa-blind","fas fa-bomb","fas fa-book","fas fa-bookmark","far fa-bookmark","fas fa-briefcase","fas fa-building","far fa-building","fas fa-car","fas fa-coffee","fas fa-crosshairs","fas fa-directions","fas fa-dollar-sign","fas fa-draw-polygon","fas fa-eye","far fa-eye","fas fa-eye-slash","far fa-eye-slash","fas fa-fighter-jet","fas fa-fire","fas fa-fire-alt","fas fa-fire-extinguisher","fas fa-flag","far fa-flag","fas fa-flag-checkered","fas fa-flask","fas fa-gamepad","fas fa-gavel","fas fa-gift","fas fa-glass-martini","fas fa-globe","fas fa-graduation-cap","fas fa-h-square","fas fa-heart","far fa-heart","fas fa-heartbeat","fas fa-helicopter","fas fa-home","fas fa-hospital","far fa-hospital","fas fa-image","far fa-image","fas fa-images","far fa-images","fas fa-industry","fas fa-info","fas fa-info-circle","fas fa-key","fas fa-landmark","fas fa-layer-group","fas fa-leaf","fas fa-lemon","far fa-lemon","fas fa-life-ring","far fa-life-ring","fas fa-lightbulb","far fa-lightbulb","fas fa-location-arrow","fas fa-low-vision","fas fa-magnet","fas fa-male","fas fa-map","far fa-map","fas fa-map-marker","fas fa-map-marker-alt","fas fa-map-pin","fas fa-map-signs","fas fa-medkit","fas fa-money-bill","fas fa-money-bill-alt","far fa-money-bill-alt","fas fa-motorcycle","fas fa-music","fas fa-newspaper","far fa-newspaper","fas fa-parking","fas fa-paw","fas fa-phone","fas fa-phone-alt","fas fa-phone-square","fas fa-phone-square-alt","fas fa-phone-volume","fas fa-plane","fas fa-plug","fas fa-plus","fas fa-plus-square","far fa-plus-square","fas fa-print","fas fa-recycle","fas fa-restroom","fas fa-road","fas fa-rocket","fas fa-route","fas fa-search","fas fa-search-minus","fas fa-search-plus","fas fa-ship","fas fa-shoe-prints","fas fa-shopping-bag","fas fa-shopping-basket","fas fa-shopping-cart","fas fa-shower","fas fa-snowplow","fas fa-street-view","fas fa-subway","fas fa-suitcase","fas fa-tag","fas fa-tags","fas fa-taxi","fas fa-thumbtack","fas fa-ticket-alt","fas fa-tint","fas fa-traffic-light","fas fa-train","fas fa-tram","fas fa-tree","fas fa-trophy","fas fa-truck","fas fa-tty","fas fa-umbrella","fas fa-university","fas fa-utensil-spoon","fas fa-utensils","fas fa-wheelchair","fas fa-wifi","fas fa-wine-glass","fas fa-wrench"]
}

/*

var names = new Set();
var icons = document.getElementById( 'results-icons' ).getElementsByTagName( 'i' );
for (const icon of icons) {
  const name = icon.className;
  names.add(name);
}
console.log(JSON.stringify(Array.from(names)));

*/